sudo: required
dist: trusty
group: edge
services:
  - docker
env:
  - NODEJS_VERSION='6'
  - NODEJS_VERSION='7'
  - NODEJS_VERSION='8'
before_install:
  - docker pull node:${NODEJS_VERSION}
  - git config --global user.name "$(git log -1 --format="format:%an")"
  - git config --global user.email "$(git log -1 --format="format:%ae")"
  - cp $HOME/.gitconfig .
  - ./travis_docker.sh /bin/bash -c "npm install --no-optional"
script:
  - ./travis_docker.sh /bin/bash -c "npm test"
after_success:
  - ./travis_docker.sh /bin/bash -c "npm run build"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  condition: "$NODEJS_VERSION = 8"
